# ==============================================================================
# Environment setup
# ==============================================================================
image: server-harbor:80/dls2/dls2-dev:22.04

stages:
   - preamble
   - build
   - deploy

before_script:
    - source /root/dls_gitlab_ci/gitlab-script.sh

# ------------------------------------------------------------------------------
# Preamble Stage
# ------------------------------------------------------------------------------
preamble:
  stage: preamble
  tags:
    - dls2
  script:
    - cmake --version
    - gcc --version
    - g++ --version

# ------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------
build:
  stage: build
  tags:
    - dls2
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - build/*
      - bin/*
    expire_in: 3 hrs

# ------------------------------------------------------------------------------
# Deploy Stage
# ------------------------------------------------------------------------------
deploy:
  stage: deploy
  tags:
    - dls2
  script:
    - cd build
    - make package
    - echo $CI_JOB_ID > CI_JOB_ID
    - source /root/dls_gitlab_ci/make-json.bash token=$DLSUSER_TOKEN project=$CI_PROJECT_ID branch=$CI_COMMIT_BRANCH job=$CI_JOB_ID tag=latest release=$(lsb_release -sc) > out.json
    - 'curl -X post -H "Content-Type: application/json" -d @out.json http://server-ubuntu18:9000/hooks/deploy-apt'
  only:
    - master
    - dls2