<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="$(find sensors_description)/urdfs/sensors/d435_camera_openni.gazebo.urdf.xacro"/>

<xacro:property name="M_PI" value="3.1415926535897931" />

<!-- The following values are approximate, and the camera node publishing TF values with actual calibrated camera extrinsic values -->
<xacro:property name="d435_cam_depth_to_left_ir_offset" value="0.0"/>
<xacro:property name="d435_cam_depth_to_right_ir_offset" value="-0.050"/>
<xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

<!-- The following values model the aluminum peripherial case for the R430 camera, with the camera joint represented by the actual peripherial camera tripod mount -->
<xacro:property name="d435_cam_width" value="0.090"/>
<xacro:property name="d435_cam_height" value="0.025"/>
<xacro:property name="d435_cam_depth" value="0.02505"/>
<xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

<!-- The following offset is relative the the physical D435 camera peripherial camera tripod mount -->
<xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
<xacro:property name="d435_cam_depth_py" value="0.0175"/>
<xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

<material name="aluminum">
	<color rgba="0.5 0.5 0.5 1"/>
</material>

<xacro:macro name="d435_camera" params="parent *origin prefix">

    
    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${prefix}/${parent}camera_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}/camera_bottom_screw_frame" />
    </joint>
    
    <link name="${prefix}/camera_bottom_screw_frame"/>

    <joint name="${prefix}/camera_link_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${prefix}/camera_bottom_screw_frame"/>
      <child link="${prefix}/camera_link" />
    </joint>


	<link name="${prefix}/camera_link">
		<visual>
			<origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
			<geometry>
				<!--box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/-->
				<mesh filename="package://realsense2_description/meshes/d435.dae" />
			</geometry>
			<material name="aluminum"/>
		</visual>
		<collision>
			<!--origin xyz="0.0 0.0 ${r430_cam_height/2}" rpy="0 0 0"/-->
			<origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
			<geometry>
				<box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
			</geometry>
		</collision>
		<!-- The following are not reliable values, and should not be used for modeling -->
		<inertial>
			<mass value="0.564" />
			<origin xyz="0 0 0" />
			<inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
		</inertial>
	</link>

	<!-- camera depth joints and links -->
	<joint name="${prefix}/camera_depth_joint" type="fixed">
		<origin xyz="0.01 0 0" rpy="0 0 0"/>
		<parent link="${prefix}/camera_link"/>
		<child link="${prefix}/camera_depth_frame" />
	</joint>
	<link name="${prefix}/camera_depth_frame"/>

	<joint name="${prefix}/camera_depth_optical_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
		<parent link="${prefix}/camera_depth_frame" />
		<child link="${prefix}/camera_depth_optical_frame" />
	</joint>
	<link name="${prefix}/camera_depth_optical_frame"/>

	<!-- camera left IR joints and links -->
	<joint name="${prefix}/camera_left_ir_joint" type="fixed">
		<origin xyz="0 ${d435_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
		<parent link="${prefix}/camera_depth_frame" />
		<child link="${prefix}/camera_left_ir_frame" />
	</joint>
	<link name="${prefix}/camera_left_ir_frame"/>

	<joint name="${prefix}/camera_left_ir_optical_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
		<parent link="${prefix}/camera_left_ir_frame" />
		<child link="${prefix}/camera_left_ir_optical_frame" />
	</joint>
	<link name="${prefix}/camera_left_ir_optical_frame"/>

	<!-- camera right IR joints and links -->
	<joint name="${prefix}/camera_right_ir_joint" type="fixed">
		<origin xyz="0 ${d435_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
		<parent link="${prefix}/camera_depth_frame" />
		<child link="${prefix}/camera_right_ir_frame" />
	</joint>
	<link name="${prefix}/camera_right_ir_frame"/>

	<joint name="${prefix}/camera_right_ir_optical_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
		<parent link="${prefix}/camera_right_ir_frame" />
		<child link="${prefix}/camera_right_ir_optical_frame" />
	</joint>
	<link name="${prefix}/camera_right_ir_optical_frame"/>

	<!-- camera color joints and links -->
	<joint name="${prefix}/camera_color_joint" type="fixed">
		<origin xyz="0.01 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
		<parent link="${prefix}/camera_depth_frame" />
		<child link="${prefix}/camera_color_frame" />
	</joint>
	<link name="${prefix}/camera_color_frame"/>

	<joint name="${prefix}/camera_color_optical_joint" type="fixed">
		<origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
		<parent link="${prefix}/camera_color_frame" />
		<child link="${prefix}/camera_color_optical_frame" />
	</joint>
	<link name="${prefix}/camera_color_optical_frame"/>

	<!-- Gazebo realsense plugin -->
	<!--xacro:d435_gazebo_camera parent="${parent}" prefix="${prefix}"/-->
	<xacro:asus_xtion_rgb_sensor prefix="${prefix}"/>

</xacro:macro>
</robot>
